[webrtc]
iceportrange = [5000, 5100]
# Use your server's public IP
icecandidates = ["YOUR_SERVER_PUBLIC_IP"]
# Enable STUN for NAT traversal
stun = ["stun:stun.l.google.com:19302"]

[log]
level = "warn"
stats = true

[router]
# Limit bandwidth per connection
maxbandwidth = "2mb"
# Max tracks per subscriber
maxpackettrack = 200

[turn]
# Disable TURN for now (can enable with credentials later)
enabled = false