version: '3.8'

services:
  ion-sfu:
    image: pionwebrtc/ion-sfu:latest
    ports:
      - "7000:7000"  # gRPC
      - "5000-5100:5000-5100/udp"  # WebRTC media
    volumes:
      - ./config.toml:/configs/sfu.toml
    environment:
      - SFU_CONFIG_FILE=/configs/sfu.toml